docker.host=${DOCKER_HOST:unix:///var/run/docker.sock}
registry.url=${DOCKER_REGISTRY_URL:https://index.docker.io/v1/}
registry.username=${DOCKER_REGISTRY_USERNAME}
registry.password=${DOCKER_REGISTRY_PASSWORD}
registry.email=${DOCKER_REGISTRY_EMAIL}